// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://fnxbiwatkmcsohpsmhck.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImZueGJpd2F0a21jc29ocHNtaGNrIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTIzMTEzOTUsImV4cCI6MjA2Nzg4NzM5NX0.LMZAm82TNmS5ApFI6ftWgA8vbhC77VaU8bV9h7LUjZA";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});